@echo off
echo Starting HostelIQ AI Engine...
cd ai-service
if not exist venv (
    echo Creating python virtual environment...
    python -m venv venv
)
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Launching FastAPI server...
python app/main.py
